spring:
  main:
    banner-mode: off
    web-application-type: none

  application:
    name: pull-request-tracker

  shell:
    interactive:
      enabled: false

logging:
  file:
    name: logs/application.log

  pattern:

    file: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'